warn and error out if base directories doesnt exist

diff --git a/svc b/svc
--- a/svc
+++ b/svc
@@ -6,8 +6,7 @@
 BASEDIR="/etc/svc.d"
 BASENAME="$(basename "$0")"
 
-[ -d "$BASEDIR" ] || mkdir -p "$BASEDIR"
-cd $BASEDIR || exit 1
+[ -d "$BASEDIR" ] || echo "Error: Base directories not found. Run svc -c to create them" && exit 1
 
 usage() {
 	printf "usage: %s [-acdklrs] [service]\n" "$BASENAME" >&2
@@ -74,14 +73,13 @@ case "$1" in
 		fi 
 		;;	
 	-c)
-		[ -d "$BASEDIR" ] || mkdir -p "$BASEDIR"
-		[ -d "$BASEDIR/avail" ] || mkdir -p "$BASEDIR/avail"
-		[ -d "$BASEDIR/run" ] || mkdir -p "$BASEDIR/run"
+		[ -d "$BASEDIR"/avail ] || mkdir -p "$BASEDIR"/avail
+		[ -d "$BASEDIR"/run ] || mkdir -p "$BASEDIR"/run
 		;;
 	-d)
 		if [ $# -gt 1 ] && [ -e "run/$2" ];
 		then
-			rm -f "run/$2"
+			rm -rf "./run/$2"
 			printf "%s: '%s' deactivated.\n" \
 				"$BASENAME" "$2"
 		else
